Repository CoffeeDrivenDevelopment/Sangchu-RecipeService, pull requests merged in 2024-04, with the labels that each got.

#4 주간 온/오프라인 데이터 정렬 수정(#2)
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/application/MarketIngredientWeeklyPriceService.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/dto/response/IngredientWeeklyPriceResponse.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/utils/IngredientWeeklyPriceUtils.java
Labels: ♻️ refactor

#3 조회 불가능한 대댓글 기능 수정
  src/main/java/com/cdd/recipeservice/global/utils/RedisUtils.java
  src/main/java/com/cdd/recipeservice/recipemodule/comment/application/RecipeCommentServiceImpl.java
  src/main/java/com/cdd/recipeservice/recipemodule/comment/domain/query/CommentRepositoryCustom.java
  src/main/java/com/cdd/recipeservice/recipemodule/comment/domain/query/CommentRepositoryImpl.java
  src/main/java/com/cdd/recipeservice/recipemodule/comment/dto/cond/PagingCond.java
  src/main/java/com/cdd/recipeservice/recipemodule/comment/dto/cond/RecipeCommentFindCond.java
  src/main/java/com/cdd/recipeservice/recipemodule/comment/dto/cond/RecipeReplyCommentFindCond.java
  src/main/java/com/cdd/recipeservice/recipemodule/comment/dto/cond/RecipeRootCommentFindCond.java
Labels: 🚑 fix, 🐛 bug

#7 댓글 NPE문제 수정
  src/main/java/com/cdd/recipeservice/recipemodule/comment/dto/response/RecipeRootCommentResponse.java
Labels: 🚑 fix, 🐛 bug

#9 Fix: 좋아요한 레시피만 넘어오도록 쿼리문 수정
  src/main/java/com/cdd/recipeservice/recipemodule/recipe/application/RecipeLikeLoadService.java
  src/main/java/com/cdd/recipeservice/recipemodule/recipe/application/RecipeLikeService.java
  src/main/java/com/cdd/recipeservice/recipemodule/recipe/application/RecipeService.java
  src/main/java/com/cdd/recipeservice/recipemodule/recipe/domain/RecipeLikeRepository.java
  src/main/java/com/cdd/recipeservice/recipemodule/recipe/dto/response/RecipeLikeDetailResponse.java
  src/main/java/com/cdd/recipeservice/recipemodule/recipe/dto/response/RecipeLikeListResponse.java
  src/main/java/com/cdd/recipeservice/recipemodule/recipe/dto/response/RecipeSearchInfo.java
  src/main/java/com/cdd/recipeservice/recipemodule/recipe/presentation/RecipeLikeController.java
Labels: 🚑 fix

#10 댓글 조회 쿼리문을 수정
  src/main/java/com/cdd/recipeservice/recipemodule/comment/domain/query/CommentRepositoryImpl.java
Labels: 🚑 fix, 🐛 bug

#12 Fix: 가격 변동 상승/하락 내림차순 최대 10개, 증감율로 넘기기
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/application/IngredientGapService.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/domain/IngredientPriceGapList.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/domain/query/IngredientSalesDailyPriceStatRepositoryCustom.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/domain/query/IngredientSalesDailyPriceStatRepositoryCustomImpl.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/dto/response/IngredientPriceGap.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/dto/response/IngredientPriceGapResponse.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/presentation/IngredientGapController.java
Labels: 🚑 fix, ♻️ refactor

#14 온라인 최저가 오름차순
  src/main/java/com/cdd/recipeservice/global/utils/LocalDateTimeUtils.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/application/MarketLowestPriceService.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/domain/MarketIngredientRepository.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/domain/query/MarketIngredientRepositoryCustom.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/domain/query/MarketIngredientRepositoryImpl.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/domain/query/MarketIngredientSalesPriceRepositoryImpl.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/domain/query/MarketRepositoryCustom.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/domain/query/MarketRepositoryCustomImpl.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/dto/response/MarketIngredientBestPrice.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/dto/response/MarketIngredientBestPriceResponse.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/dto/response/MarketLowestPriceListResponse.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/dto/response/OnlineMarket.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/presentation/MarketLowestPriceController.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/utils/ClosestMarketUtils.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/utils/MarketIngredientLowestPriceUtils.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/targetprice/application/TargetPriceService.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/application/IngredientBestPriceService.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/application/IngredientGapService.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/application/MarketIngredientWeeklyPriceService.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/domain/query/IngredientSalesDailyPriceStatRepositoryCustom.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/domain/query/IngredientSalesDailyPriceStatRepositoryCustomImpl.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/dto/cond/PriceSearchCond.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/presentation/IngredientBestPriceController.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/utils/IngredientSalesDailyPriceStatUtils.java
  src/main/java/com/cdd/recipeservice/recipemodule/recipe/utils/RecipeLikeMapper.java
Labels: 🚑 fix, ♻️ refactor

#17 온라인 마켓의 최저가 목록을 수정(#16)
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/application/MarketLowestPriceService.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/domain/query/MarketRepositoryCustomImpl.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/utils/MarketIngredientLowestPriceUtils.java
  src/main/java/com/cdd/recipeservice/recipemodule/review/domain/CookEat.java
Labels: 🚑 fix, 🐛 bug

#19 Fetch Join 사용(#16)
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/application/MarketLowestPriceService.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/domain/query/MarketRepositoryCustom.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/domain/query/MarketRepositoryCustomImpl.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/dto/response/OnlineMarket.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/utils/MarketIngredientLowestPriceUtils.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/application/MarketIngredientWeeklyPriceService.java
Labels: 🚑 fix, 🐛 bug

#20 MarketIngredient FetchJoin 사용(#16)
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/domain/query/MarketRepositoryCustomImpl.java
Labels: 🚑 fix, 🐛 bug

#21 Fix: 데이터가 캐싱된 시간 updateAt 넘기기
  src/main/java/com/cdd/recipeservice/ingredientmodule/ingredient/application/RecommendIngredientServiceImpl.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/ingredient/domain/RecommendIngredient.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/ingredient/dto/response/IngredientInfo.java
Labels: ♻️ refactor

#23 주간 데이터 저장시 데이터가 캐싱된 시간 updateAt 넘기기(#22)
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/dto/response/MarketPricePerUserResponse.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/application/MarketIngredientWeeklyPriceService.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/domain/IngredientWeeklyPrice.java
Labels: 🚑 fix, ♻️ refactor

#25 가격 변동 식재료 카테고리 추천 쿼리문 수정(#24)
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/domain/query/IngredientSalesDailyPriceStatRepositoryCustomImpl.java
Labels: 🚑 fix, ♻️ refactor

#27 온/오프라인 평균 조회(#26)
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/application/MarketIngredientWeeklyPriceService.java
Labels: 🚑 fix

#29 Fix: 3km이내 시장 데이터 조회
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/domain/query/MarketRepositoryCustomImpl.java
Labels: 🚑 fix

#31 온/오프라인 가격 분석 상세조회 쿼리문 수정(#30)
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/domain/query/MarketRepositoryCustomImpl.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/application/MarketIngredientWeeklyPriceService.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/weeklyprice/utils/IngredientWeeklyPriceUtils.java
Labels: 🚑 fix

#33 회원 오프라인 데이터 조회 기능 수정
  src/main/java/com/cdd/recipeservice/infra/member/application/MemberClient.java
  src/main/java/com/cdd/recipeservice/infra/member/application/MemberClientImpl.java
  src/main/java/com/cdd/recipeservice/infra/member/dto/MemberCoordinateResponse.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/application/MarketLowestPriceService.java
  src/main/java/com/cdd/recipeservice/ingredientmodule/market/presentation/MarketLowestPriceController.java
  src/main/java/com/cdd/recipeservice/recipemodule/recipe/presentation/RecipeLikeController.java
  src/main/java/com/cdd/recipeservice/recipemodule/review/application/CookEatService.java
Labels: 🚑 fix, 🐛 bug
